/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author launa
 */
public class superstring extends javax.swing.JFrame {

    /**
     * Creates new form superstring
     */
    public superstring() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foursixlbl = new javax.swing.JPanel();
        tltlbl = new javax.swing.JLabel();
        lengthlbl = new javax.swing.JLabel();
        lengthtxt = new javax.swing.JTextField();
        lengthbtn = new javax.swing.JButton();
        upperlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        charlbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        letterlbl = new javax.swing.JLabel();
        replacelbl = new javax.swing.JLabel();
        uppertxt = new javax.swing.JTextField();
        upperbtn = new javax.swing.JButton();
        chartxt = new javax.swing.JTextField();
        identxt1 = new javax.swing.JTextField();
        lettertxt = new javax.swing.JTextField();
        foursixtxt = new javax.swing.JTextField();
        replacetxt = new javax.swing.JTextField();
        charbtn = new javax.swing.JButton();
        identbtn = new javax.swing.JButton();
        letterbtn = new javax.swing.JButton();
        foursixbtn = new javax.swing.JButton();
        replacebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lengthanslbl = new javax.swing.JLabel();
        upperanslbl = new javax.swing.JLabel();
        charanslbl = new javax.swing.JLabel();
        identxt2 = new javax.swing.JTextField();
        identanslbl = new javax.swing.JLabel();
        lettertxt2 = new javax.swing.JTextField();
        letteranslbl = new javax.swing.JLabel();
        fourtosixanslbl = new javax.swing.JLabel();
        replaceanslbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tltlbl.setText("Super String Software");

        lengthlbl.setText("Enter a String. This program will output the number of characters in the String. ");

        lengthtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthtxtActionPerformed(evt);
            }
        });

        lengthbtn.setText("Length");
        lengthbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthbtnActionPerformed(evt);
            }
        });

        upperlbl.setText("Enter a String in lowercase letters. This program will output it in uppercase letters.");

        jLabel3.setText("Enter a String that is at least 8 characters long. This program will output characters 4-6.");

        charlbl.setText("Enter a String. This program will output the character at the 4th spot. ");

        jLabel5.setText("Enter two Strings. This program will output whether they are identical or not.");

        letterlbl.setText("Enter a String and a letter. This program output whether or not the letter is found in the String. ");

        replacelbl.setText("Enter a String that contains at least one \"a\" This program will replace \"a\" with the letter \"x\"");

        upperbtn.setText("Uppercase");
        upperbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperbtnActionPerformed(evt);
            }
        });

        chartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartxtActionPerformed(evt);
            }
        });

        identxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identxt1ActionPerformed(evt);
            }
        });

        foursixtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursixtxtActionPerformed(evt);
            }
        });

        replacetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacetxtActionPerformed(evt);
            }
        });

        charbtn.setText("4th Character");
        charbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charbtnActionPerformed(evt);
            }
        });

        identbtn.setText("identical?");
        identbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identbtnActionPerformed(evt);
            }
        });

        letterbtn.setText("letter?");
        letterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterbtnActionPerformed(evt);
            }
        });

        foursixbtn.setText("characters 4 to 6");
        foursixbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursixbtnActionPerformed(evt);
            }
        });

        replacebtn.setText("Replace");
        replacebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacebtnActionPerformed(evt);
            }
        });

        lengthanslbl.setText("...");

        upperanslbl.setText("...");

        charanslbl.setText("...");

        identanslbl.setText("...");

        lettertxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettertxt2ActionPerformed(evt);
            }
        });

        letteranslbl.setText("...");

        fourtosixanslbl.setText("...");

        replaceanslbl.setText("...");

        javax.swing.GroupLayout foursixlblLayout = new javax.swing.GroupLayout(foursixlbl);
        foursixlbl.setLayout(foursixlblLayout);
        foursixlblLayout.setHorizontalGroup(
            foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foursixlblLayout.createSequentialGroup()
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(foursixlblLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lengthtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(uppertxt))
                        .addGap(18, 18, 18)
                        .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addComponent(upperbtn)
                                .addGap(29, 29, 29)
                                .addComponent(upperanslbl))
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lengthbtn)
                                .addGap(41, 41, 41)
                                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lengthanslbl)
                                    .addComponent(jLabel1)))))
                    .addGroup(foursixlblLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letterlbl)
                            .addComponent(lengthlbl)
                            .addComponent(upperlbl)
                            .addComponent(charlbl)
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addComponent(chartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(charbtn)
                                .addGap(18, 18, 18)
                                .addComponent(charanslbl))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(replacelbl)
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addComponent(identxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(identxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(identbtn)
                                .addGap(36, 36, 36)
                                .addComponent(identanslbl))
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addComponent(lettertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lettertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(letterbtn)
                                .addGap(18, 18, 18)
                                .addComponent(letteranslbl))
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addComponent(foursixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(foursixbtn)
                                .addGap(31, 31, 31)
                                .addComponent(fourtosixanslbl))
                            .addGroup(foursixlblLayout.createSequentialGroup()
                                .addComponent(replacetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(replacebtn)
                                .addGap(28, 28, 28)
                                .addComponent(replaceanslbl))))
                    .addGroup(foursixlblLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(tltlbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        foursixlblLayout.setVerticalGroup(
            foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foursixlblLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tltlbl)
                .addGap(33, 33, 33)
                .addComponent(lengthlbl)
                .addGap(8, 8, 8)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthbtn)
                    .addComponent(jLabel1)
                    .addComponent(lengthanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upperlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uppertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upperbtn)
                    .addComponent(upperanslbl))
                .addGap(18, 18, 18)
                .addComponent(charlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charbtn)
                    .addComponent(charanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identbtn)
                    .addComponent(identxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letterlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lettertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letterbtn)
                    .addComponent(lettertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letteranslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foursixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foursixbtn)
                    .addComponent(fourtosixanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replacelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(foursixlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replacetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replacebtn)
                    .addComponent(replaceanslbl))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(foursixlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(foursixlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthtxtActionPerformed

    private void chartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chartxtActionPerformed

    private void identxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identxt1ActionPerformed

    private void lengthbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthbtnActionPerformed
        String txt1; 
        
        txt1 = lengthtxt.getText();
        lengthanslbl.setText((txt1.length()));
        
        
        
     
    }//GEN-LAST:event_lengthbtnActionPerformed

    private void upperbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperbtnActionPerformed
        String txt1; 
        
        txt1 = uppertxt.getText();
        upperanslbl.setText(txt1.toUpperCase());
        
        
    }//GEN-LAST:event_upperbtnActionPerformed

    private void charbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charbtnActionPerformed
        String txt1;
        txt1 = chartxt.getText();
        charanslbl.setText(txt1.charAt(4));
    }//GEN-LAST:event_charbtnActionPerformed

    private void identbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identbtnActionPerformed
        String txt1;
        String txt2;
        
        txt1 = identxt1.getText();
        txt2 = identxt2.getText();
        
        if (txt1.equals(txt2))
        identanslbl.setText("yes!");
        
        else 
        identanslbl.setText("no!");
        
        
    }//GEN-LAST:event_identbtnActionPerformed

    private void foursixtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursixtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foursixtxtActionPerformed

    private void lettertxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettertxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lettertxt2ActionPerformed

    private void letterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterbtnActionPerformed
        String txt1;
        String txt2;
        
        txt1 = lettertxt.getText();
        txt2 = lettertxt2.getText();
        
        if (txt1.contains(txt2))
        {
            letteranslbl.setText ("yes!");
            
        }
        
        else 
        {
            letteranslbl.setText("no!");
        }
    }//GEN-LAST:event_letterbtnActionPerformed

    private void foursixbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursixbtnActionPerformed
        String txt1;
        
        txt1 = foursixtxt.getText();
        
        fourtosixanslbl.setText(txt1.substring(4,7));
    }//GEN-LAST:event_foursixbtnActionPerformed

    private void replacetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replacetxtActionPerformed

    private void replacebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacebtnActionPerformed
        String txt1;
         
        txt1 = replacetxt.getText();
        
        replaceanslbl.setText(txt1.replace("a","x"));
    }//GEN-LAST:event_replacebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superstring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superstring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superstring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superstring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superstring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel charanslbl;
    private javax.swing.JButton charbtn;
    private javax.swing.JLabel charlbl;
    private javax.swing.JTextField chartxt;
    private javax.swing.JButton foursixbtn;
    private javax.swing.JPanel foursixlbl;
    private javax.swing.JTextField foursixtxt;
    private javax.swing.JLabel fourtosixanslbl;
    private javax.swing.JLabel identanslbl;
    private javax.swing.JButton identbtn;
    private javax.swing.JTextField identxt1;
    private javax.swing.JTextField identxt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lengthanslbl;
    private javax.swing.JButton lengthbtn;
    private javax.swing.JLabel lengthlbl;
    private javax.swing.JTextField lengthtxt;
    private javax.swing.JLabel letteranslbl;
    private javax.swing.JButton letterbtn;
    private javax.swing.JLabel letterlbl;
    private javax.swing.JTextField lettertxt;
    private javax.swing.JTextField lettertxt2;
    private javax.swing.JLabel replaceanslbl;
    private javax.swing.JButton replacebtn;
    private javax.swing.JLabel replacelbl;
    private javax.swing.JTextField replacetxt;
    private javax.swing.JLabel tltlbl;
    private javax.swing.JLabel upperanslbl;
    private javax.swing.JButton upperbtn;
    private javax.swing.JLabel upperlbl;
    private javax.swing.JTextField uppertxt;
    // End of variables declaration//GEN-END:variables
}
